alias: flying-monkey
apiVersion: kargo.akuity.io/v1alpha1
commits:
- branch: main
  id: <commit-sha>
  message: '<commit-msg>'
  repoURL: https://github.com/morey-tech/intro-argo-cd-kargo-demo
images:
- digest: sha256:57f27650e10ae33978bc14c80c90b7688ecad3950b308d1ec157c9495ebcefc4
  repoURL: quay.io/akuity/argo-cd-learning-assets/guestbook
  tag: 0.1.0
kind: Freight
metadata:
  labels:
    kargo.akuity.com/v0.5-compatible: "true"
    kargo.akuity.io/alias: flying-monkey
  name: placeholder-0.1.0
  namespace: kargo-demo
warehouse: kargo-demo
---
alias: sprinting-chipmunk
apiVersion: kargo.akuity.io/v1alpha1
commits:
- branch: main
  id: <commit-sha>
  message: '<commit-msg>'
  repoURL: https://github.com/morey-tech/intro-argo-cd-kargo-demo
images:
- digest: sha256:57f27650e10ae33978bc14c80c90b7688ecad3950b308d1ec157c9495ebcefc4
  repoURL: quay.io/akuity/argo-cd-learning-assets/guestbook
  tag: 0.2.0
kind: Freight
metadata:
  labels:
    kargo.akuity.com/v0.5-compatible: "true"
    kargo.akuity.io/alias: sprinting-chipmunk
  name: placeholder-0.2.0
  namespace: kargo-demo
warehouse: kargo-demo
---
alias: screaming-dolphin
apiVersion: kargo.akuity.io/v1alpha1
commits:
- branch: main
  id: <commit-sha>
  message: '<commit-msg>'
  repoURL: https://github.com/morey-tech/intro-argo-cd-kargo-demo
images:
- digest: sha256:57f27650e10ae33978bc14c80c90b7688ecad3950b308d1ec157c9495ebcefc4
  repoURL: quay.io/akuity/argo-cd-learning-assets/guestbook
  tag: 0.3.0
kind: Freight
metadata:
  labels:
    kargo.akuity.com/v0.5-compatible: "true"
    kargo.akuity.io/alias: screaming-dolphin
  name: placeholder-0.3.0
  namespace: kargo-demo
warehouse: kargo-demo